name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start the service with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      description: Which implementation are you using?
      options:
        - BigBrotr (full-featured)
        - LilBrotr (lightweight)
        - Custom implementation
        - N/A
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Affected Service
      description: Which service is affected?
      options:
        - Initializer
        - Finder
        - Monitor
        - Synchronizer
        - Core (Pool/Brotr)
        - Database
        - Docker/Deployment
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of BigBrotr are you using?
      placeholder: "2.0.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11
        - PostgreSQL: 16
        - Docker: 24.0.5
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
