# ============================================================================
# Initializer Service Configuration
# ============================================================================
# Description: Bootstrap database and seed initial data
# Used by: src/services/initializer.py
# Priority: CRITICAL (needed for all other services)
# ============================================================================

# Database operations
database:
  verify_tables: true           # Verify database tables exist
  verify_procedures: true       # Verify stored procedures exist
  verify_extensions: true       # Verify PostgreSQL extensions

# Schema files to verify (relative to implementations/bigbrotr/)
schema_files:
  extensions: postgres/init/00_extensions.sql
  utility_functions: postgres/init/01_utility_functions.sql
  tables: postgres/init/02_tables.sql
  indexes: postgres/init/03_indexes.sql
  integrity_functions: postgres/init/04_integrity_functions.sql
  procedures: postgres/init/05_procedures.sql
  views: postgres/init/06_views.sql
  verify: postgres/init/99_verify.sql

# Expected stored procedures (for verification)
expected_procedures:
  - insert_event
  - insert_relay
  - insert_relay_metadata
  - delete_orphan_events
  - delete_orphan_nip11
  - delete_orphan_nip66

# Expected tables (for verification)
expected_tables:
  - relays
  - events
  - events_relays
  - nip11
  - nip66
  - relay_metadata
  - service_state

# Expected extensions (for verification)
expected_extensions:
  - pgcrypto   # For hashing functions (digest)
  - btree_gin  # For GIN indexes on tagvalues array

# Seed data configuration
# Note: Network type (clearnet/tor) is auto-detected from URL using nostr_tools.Relay
# Note: Duplicate URLs are ignored by the database (ON CONFLICT DO NOTHING)
seed_data:
  enabled: true                           # Enable seed data loading
  relay_file: data/seed_relays.txt        # Path to relay file (relative to implementations/bigbrotr/)
  batch_size: 100                         # Insert relays in batches of 100

# Logging configuration
logging:
  log_verification_details: true   # Log each verification step
  log_seed_progress: true          # Log seed data loading progress
  log_level: INFO

# Timeouts
timeouts:
  schema_verification: 30.0     # Timeout for schema checks (seconds)
  seed_data_load: 300.0         # Timeout for seed data loading (seconds)

# Retry configuration for database operations
retry:
  max_attempts: 3               # Maximum retry attempts for DB operations
  initial_delay: 1.0            # Initial delay between retries (seconds)
  max_delay: 10.0               # Maximum delay between retries (seconds)
  exponential_backoff: true     # Use exponential backoff
