# ============================================================================
# Monitor Service Configuration
# ============================================================================
# Description: Monitor relay health and capabilities (NIP-11, NIP-66)
# Used by: src/services/monitor.py
# Dependencies: Finder must have discovered relays first
# ============================================================================

# Tor proxy for .onion relays
tor_proxy:
  enabled: true
  host: "tor"
  port: 9050

# Nostr keys for NIP-66 write tests (optional)
# Public key is configured here, private key from MONITOR_PRIVATE_KEY env var
keys:
  public_key: null  # Public key (hex) for write tests

# Timeout settings for relay checks
timeouts:
  clearnet: 30.0  # Timeout for clearnet relay checks (seconds)
  tor: 60.0  # Timeout for Tor relay checks (seconds)

# Concurrency settings
concurrency:
  max_concurrent: 50  # Maximum concurrent relay checks
  batch_size: 50  # Relays to process before pushing to database

# Relay selection configuration
relay_selection:
  min_check_age: 3600  # Minimum seconds since last check (1 hour)

# Interval between monitor cycles (seconds)
monitor_interval: 3600.0  # 1 hour