# ============================================================================
# Monitor Service Configuration (BigBrotr)
# ============================================================================
# Description: Monitor relay health and capabilities with full NIP-66 compliance
# Used by: src/services/monitor.py
# Dependencies: Validator must have validated relays first
# Environment: PRIVATE_KEY required if publishing enabled
# Notes: Uses overlay network proxies for hidden relay monitoring (.onion, .i2p, .loki)
# ============================================================================

# Cycle interval (seconds between monitoring runs)
# Range: >= 60.0
interval: 3600.0

# Prometheus metrics and health checks
metrics:
  enabled: true
  port: 8003
  host: "0.0.0.0"
  path: "/metrics"
  health:
    max_cycle_age_seconds: 7200.0    # Unhealthy if no cycle in 2 hours

# Unified network configuration
# Each network type has: enabled, proxy_url, max_tasks, timeout
networks:
  clearnet:
    enabled: true
    max_tasks: 50              # High concurrency for fast clearnet relays
    timeout: 30.0              # Timeout for relay checks

  tor:
    enabled: true
    proxy_url: "socks5://tor:9050"
    max_tasks: 10              # Lower concurrency (Tor is slower)
    timeout: 60.0              # Longer timeout for Tor latency

  i2p:
    enabled: false             # Disabled by default (enable i2p service in docker-compose first)
    proxy_url: "socks5://i2p:4447"
    max_tasks: 5               # Even lower (I2P is slowest)
    timeout: 90.0              # Longest timeout for I2P

  loki:
    enabled: false             # Disabled by default (requires Lokinet - Linux only)
    proxy_url: "socks5://lokinet:1080"
    max_tasks: 5
    timeout: 60.0

# Nostr keys for NIP-66 events
# Private key is loaded from PRIVATE_KEY environment variable
keys: {}

# NIP-66 event publishing configuration
publishing:
  enabled: true              # Enable publishing Kind 30166/10166 events
  # Destination options:
  #   - "monitored_relay": Publish Kind 30166 on the relay being checked (default)
  #   - "configured_relays": Publish to relays listed below
  #   - "database_only": No Nostr publishing, only store in database
  destination: "monitored_relay"
  # Relays for publishing (only used if destination: "configured_relays")
  relays: []

# Checks to perform on each relay
checks:
  open: true                 # Test WebSocket connection
  read: true                 # Test REQ/EOSE subscription
  write: true                # Test EVENT/OK publication (requires PRIVATE_KEY)
  nip11: true                # Fetch NIP-11 relay info document
  ssl: true                  # Validate SSL/TLS certificate
  dns: true                  # Measure DNS resolution time
  geo: true                  # Geolocate relay IP address

# Geolocation configuration
# Requires MaxMind GeoLite2 databases (free with registration)
# Download from: https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
# Place databases in static/ folder
geo:
  city_database_path: "static/GeoLite2-City.mmdb"
  asn_database_path: "static/GeoLite2-ASN.mmdb"  # Optional, for ASN/ISP info
  country_database_path: "static/GeoLite2-Country.mmdb"  # Optional, for country fallback
  # Update frequency: "monthly", "weekly", "none" (none = never auto-update)
  update_frequency: "monthly"

# Concurrency settings
concurrency:
  max_processes: 1           # Number of worker processes (Range: 1 - 32)
  batch_size: 50             # Relays to process before pushing to database (Range: 1 - 500)

# Relay selection - which relays to check
selection:
  min_age_since_check: 3600  # Minimum seconds since last check (Range: >= 0)
