# ============================================================================
# Finder Service Configuration (LilBrotr)
# ============================================================================
# Description: Discover Nostr relay URLs from external APIs and database events
# Used by: src/services/finder.py
# Dependencies: Seeder must complete first
# Notes: Discovered URLs are stored as candidates in the service_data table
#        with service_name='validator' for validation before adding to relays
# ============================================================================

# Cycle interval (seconds between discovery runs)
# Range: >= 60.0
interval: 3600.0

# Prometheus metrics
metrics:
  enabled: true
  port: 8001
  host: "0.0.0.0"
  path: "/metrics"

# Event scanning - discovers relay URLs from stored events
# NOTE: Disabled for LilBrotr because it does not store tags/tagvalues/content columns
# which are required for event scanning. Enable only if using full schema.
events:
  enabled: false                  # Disabled - LilBrotr lacks tags/content columns
  batch_size: 1000                # Events to process per batch (Range: 100-10000)
  kinds: [2, 3, 10002]            # Event kinds: 2=recommend relay, 3=contacts, 10002=relay list

# External API - discovers relay URLs from public APIs
api:
  enabled: true                   # Enable API fetching
  verify_ssl: true                # Verify TLS certificates (disable only for testing)
  sources:
    - url: https://api.nostr.watch/v1/online
      enabled: true
      timeout: 30.0               # Range: 0.1 - 120.0
    - url: https://api.nostr.watch/v1/offline
      enabled: true
      timeout: 30.0               # Range: 0.1 - 120.0
  delay_between_requests: 1.0     # Range: 0.0 - 10.0

# Concurrency settings
concurrency:
  max_parallel: 5            # Maximum concurrent API requests (Range: 1 - 20)
