# ============================================================================
# Monitor Service Configuration (LilBrotr)
# ============================================================================
# Description: Monitor relay health and capabilities with full NIP-66 compliance
# Note: Lighter configuration - only overrides from defaults are listed
# See: implementations/bigbrotr/yaml/services/monitor.yaml for full config
# Environment: PRIVATE_KEY required if publishing enabled
# ============================================================================

# Unified network configuration (clearnet only for lilbrotr)
networks:
  clearnet:
    enabled: true
    max_tasks: 20              # Reduced concurrency for lighter resource usage
    timeout: 30.0

  tor:
    enabled: false
    proxy_url: "socks5://tor:9050"
    max_tasks: 5
    timeout: 60.0

  i2p:
    enabled: false
    proxy_url: "socks5://i2p:4447"
    max_tasks: 3
    timeout: 90.0

  loki:
    enabled: false
    proxy_url: "socks5://lokinet:1080"
    max_tasks: 3
    timeout: 60.0

# NIP-66 event publishing configuration
publishing:
  enabled: true
  destination: "monitored_relay"

# Geolocation configuration
# Place databases in static/ folder
geo:
  city_database_path: "static/GeoLite2-City.mmdb"
  # ASN database optional for lilbrotr
  # asn_database_path: "static/GeoLite2-ASN.mmdb"
  # Update frequency: "monthly", "weekly", "none" (none = never auto-update)
  update_frequency: "none"  # Manual updates only for lilbrotr

# Reduced concurrency for lighter resource usage
concurrency:
  max_processes: 1           # Number of worker processes
  batch_size: 20             # Relays to process before pushing to database
