# ============================================================================
# Monitor Service Configuration (LilBrotr)
# ============================================================================
# Description: Monitor relay health and capabilities (NIP-11, NIP-66)
# Note: Lighter configuration - only overrides from defaults are listed
# See: implementations/bigbrotr/yaml/services/monitor.yaml for full config
# ============================================================================

# Tor proxy disabled for lilbrotr (clearnet only)
tor:
  enabled: false

# Reduced concurrency for lighter resource usage
concurrency:
  max_parallel: 10
  batch_size: 25